### ISSUE TITLE
Memory leaks on MacOS Mojave 

### ISSUE THREAD

**Issue by tiksem** [ollix/MetalNanoVG#10]
I created a simple app with nvgBeginFrame and nvgEndFrame only. And there are memory leaks there. I guess It's somehow related with mtlnvg__renderFlush. When I comment code there it doesn't produce the leaks.

**Comment by olliwang** [comment]
Can you try if the ARC branch has memory leaks, too?

**Comment by tiksem** [comment]
I didn't try with ARC. But I guess I fixed it. The problem is here:
[buffers->commandBuffer addCompletedHandler:^(id<MTLCommandBuffer> buffer) {
        buffers->isBusy = NO;
        [buffers->commandBuffer release];
        buffers->commandBuffer = nil;
        buffers->image = 0;
        buffers->nindexes = 0;
        buffers->nverts = 0;
        buffers->npaths = 0;
        buffers->ncalls = 0;
        buffers->nuniforms = 0;
        dispatch_semaphore_signal(mtl->semaphore);
    }];
I added [buffers->commandBuffer release];

**Comment by olliwang** [comment]
It seems adding this line would cause runtime error on iOS since it's in `@autoreleasepool` block.

**Comment by tiksem** [comment]
I am not an expert in non-ARC Objective-C. Are all the blocks belong to autorelasepool as well?

**Comment by olliwang** [comment]
You can find the related `@autoreleasepool` statement at https://github.com/ollix/MetalNanoVG/blob/2721f62b5131b4c51e0ba1389f1a6f59174ed2d2/src/nanovg_mtl.m#L1266

Since ARC branch will be merged into the master branch. Can you test if it fixes this issue?

**Comment by tiksem** [comment]
Yes, I see. I mean, Objective-C closures ^() belong to this autoreleasepool as well?

**Comment by olliwang** [comment]
> Yes, I see. I mean, Objective-C closures ^() belong to this autoreleasepool as well?

I am not sure, but adding `[buffers->commandBuffer release]` will cause runtime error on iOS for sure.

**Comment by olliwang** [comment]
MetalNanoVG now officially requires ARC. https://github.com/ollix/MetalNanoVG/commit/8c212e8aff0d15fc7959886c46e031103867ab99 Please try the latest commit and check if there's still memory leaks.

**Comment by olliwang** [comment]
@tiksem Can you confirm if there are still memory leaks?

**Comment by tiksem** [comment]
@olliwang I've just checked, there are no leaks on master.
