### ISSUE TITLE
MetalNanoVG changes drawable pixel format to MTLPixelFormatBGRA8Unorm

### ISSUE THREAD

**Issue by wtholliday** [ollix/MetalNanoVG#11]
Before drawing, the pixel format is: `MTLPixelFormatBGRA10_XR_sRGB`, as I set in the storyboard.

After drawing, pixel format changed to: `MTLPixelFormatBGRA8Unorm`.

Looks like it's getting changed in `mtlnvg__renderCreate`.

Should MetalNanoVG respect the existing pixel format?

**Comment by wtholliday** [comment]
Seems like `mtlnvg__renderCreateTexture` would have to get the pixel format from the `MNVGcontext` instead of setting it to `MTLPixelFormatRGBA8Unorm`.

**Comment by olliwang** [comment]
I never used other pixel format. Does it work if you comment out https://github.com/ollix/MetalNanoVG/blob/4f0ec7320af079624978ff893fcdda86b3b251a8/src/nanovg_mtl.m#L809 in your case?

**Comment by wtholliday** [comment]
Yes, it seems to.

**Comment by olliwang** [comment]
Thanks. Just fixed in https://github.com/ollix/MetalNanoVG/commit/8b281343bcc596fa35fcb20391629101fd93da33. :)
