### ISSUE TITLE
mtlnvg__renderDelete crash (old version)

### ISSUE THREAD

**Issue by olilarkin** [ollix/MetalNanoVG#15]
I'm experiencing an occasional crash when quitting my application and destroying the Nanovg context.  There is a message on the console,  

BUG IN CLIENT OF LIBDISPATCH: Semaphore object deallocated while in use

which led me to  this workaround https://lists.apple.com/archives/cocoa-dev/2014/Apr/msg00484.html

Not yet sure if this completely fixes it
https://github.com/iPlug2/iPlug2/commit/2526e838c7515b16e3c66e3edd7dae7f2712c675

I'm currently stuck with an older version of MetalNanoVG,  because with the latest I am getting some deadlocks that didn't happen before (https://github.com/iPlug2/iPlug2/issues/152)( but maybe due to incorrect use).  I need to investigate in a barebones app. However,  it looks like the dispatch_semaphore_create call is similar

 would be possible to explain the usage of libdispatch in MetalNanoVG,  so I can try and better understand the problems?

**Comment by olliwang** [comment]
That's a bit weird. Your solution should have the same meaning as the original one. Maybe the deadlock is caused because the semaphore blocks the main thread. But the rendering time is usually pretty short and shouldn't be a problem. https://stackoverflow.com/questions/23567572/semaphore-wait-causing-a-block-of-afnetworking

Make sure each `nvgBeginFrame()` is followed by either `nvgEndFrame()` or `nvgCancelFrame()` so the semaphore works as expected.

**Comment by olilarkin** [comment]
If I want to render something to an fbo, can that be done inside a main begin/endframe pair?

**Comment by olliwang** [comment]
You need `nvgBeginFrame()` and `nvgEndFrame()` for every FBO. The correct way to use FBO is something like...

    # Creates a FBO
    MNVGframebuffer* fb = mnvgCreateFramebuffer(ctx, ...)

    # Uses the FBO
    mnvgBindFramebuffer(fb)
    nvgBeginFrame(ctx, ...)
    ... # drawing something
    nvgEndFrame(ctx);
    nvgBindFramebuffer(NULL);
    
    ...
    
    # Deletes the FBO
    mnvgDeleteFramebuffer(fb)

**Comment by AlexHarker** [comment]
Hi @olliwang - I did the FBO stuff for IPlug2 - it looks like we probably are not always balanced in our calls (more calls nvgEndFrame() than nvgBeginFrame()) 

- Am I right that this could be the issue?

**Comment by AlexHarker** [comment]
So - I balanced our calls but it didn't fix the issue so I've taken more of a look at the semaphore calls, having done enough threading in the past to have a reasonable idea of how things work.

The logic of the semaphores is totally unclear to me. It seems to be linked to the number of frame buffers for backing, but here we are starting and finishing FBOs for our own purposes a lot of the time.

@olliwang  - would you mind explaining what this code is trying to do? It may be that I've misunderstood it, but I can't figure out how it is protecting the progression of events in a way that makes sense here.A single semaphore to protect multiple resources seems a bit strange to me.

**Comment by olliwang** [comment]
@AlexHarker You can't have more `nvgEndFrame()` than `nvgBeginFrame()`.

About semaphore, please check Apple's official guide at https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/TripleBuffering.html

**Comment by AlexHarker** [comment]
Thanks - yes - now I see that this is doing threading things I can see the need for a blanked count.

I think I am getting to grips with the semaphore at the moment, but it is still blocking in our case, although I have demonstrated our calls to be balanced - I'll do some more digging to see what I can find.

**Comment by AlexHarker** [comment]
OK - thanks for the noise - I checked my balancing in the wrong place and now I've checked the balancing directly in MetalNanoVG I've managed to correct the blanking *properly*.

Sorry for the noise.

**Comment by olilarkin** [comment]
closing this, since we think it was due to mismatched nvgEndFrame() /  nvgBeginFrame
