### ISSUE TITLE
Option to present drawable?

### ISSUE THREAD

**Issue by olilarkin** [ollix/MetalNanoVG#16]
Might be that I don't understand metal well enough yet, but I was wondering if there could be an option whether MetalNanoVG calls presentDrawable or not.  I have been trying to render  ImGui on top of a MetalNanoVG scene,  which in its metal example implementation, also calls present drawable.  currently in order to avoid flickering I need to comment out the MetalNanoVG presentDrawable

**Comment by olliwang** [comment]
I'm not familiar with ImGui. Can you create a mini project utilizing MetalNanoVG and ImGui together?

**Comment by olilarkin** [comment]
here you go

https://github.com/olilarkin/TestNVGMetal/tree/imgui

without disabling MetalNanoVG's 

```  
if (drawable) {
    [buffers.commandBuffer presentDrawable:drawable];
  }
```

i get a lot of flicker

**Comment by olliwang** [comment]
It seems I can't reproduce the effects.

<img width="611" alt="Screen Shot 2019-04-15 at 1 22 37 PM" src="https://user-images.githubusercontent.com/76374/56109122-c14d4f80-5f81-11e9-8f46-3136aeb153aa.png">

After commenting out the line.

<img width="611" alt="Screen Shot 2019-04-15 at 1 22 44 PM" src="https://user-images.githubusercontent.com/76374/56109142-d1652f00-5f81-11e9-9697-f98375c97d21.png">

**Comment by olliwang** [comment]
It seems there are a lot of issues when running on my iMac. https://youtu.be/eElp8SIoECc

<img width="698" alt="Screen Shot 2019-04-15 at 1 41 00 PM" src="https://user-images.githubusercontent.com/76374/56109781-9f090100-5f84-11e9-95d2-9fa734b327cf.png">

**Comment by olilarkin** [comment]
Yes I’ve also seen there are still some  issues even with those lines commented. Do you have any suggestions about the correct way to carry on drawing extra geometry  on top of a nanovg metal scene?  I was thinking perhaps I should investigate rendering the imgui layer to a separate calayer

**Comment by olliwang** [comment]
Yeah, I think you should use separated metal layers, too. I dealt with a similar situation of mixing nanovg stuff and some native views (e.g. map, text field, etc). I'd suggest trying to avoid such scenarios unless there is no other way.

**Comment by olilarkin** [comment]
thanks, i solved it with a 2nd transparent MTKView. Maybe more heavy, but this is only debug gui anyway
