### ISSUE TITLE
Why is ARC not supported?

### ISSUE THREAD

**Issue by wtholliday** [ollix/MetalNanoVG#2]
It seems like there would be no problem supporting it. And almost all ObjC code now uses ARC.

**Comment by wtholliday** [comment]
Also, would `-fno-objc-arc` for only `nanovg_mtl.m` work instead of a separate library?

**Comment by olliwang** [comment]
It is possible to support ARC. However, MetalNanoVG tries to follow the coding style of `nanovg_gl.h`. So a lot of Objective C variables are kept in C structs, and that is ARC unfriendly. I'm not sure whether `-fno-objc-arc` works or not, maybe you can try.

**Comment by wtholliday** [comment]
Couldn't you simply set the variables to nil wherever you call release?

**Comment by olliwang** [comment]
That wouldn't work. Check Apple's ARC guide: https://developer.apple.com/library/content/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html

As I said, it's still possible to make MetalNanoVG to be compatible with ARC, but that requires some additional work. And I don't have time to do it in a near future. If you finished it, I'd be happy to test it.

**Comment by wtholliday** [comment]
`-fno-objc-arc` compiles at least :)

**Comment by olliwang** [comment]
Cheers!

**Comment by olliwang** [comment]
I've created a new branch for ARC support. Can anyone check the functionality? https://github.com/ollix/MetalNanoVG/commit/3e4da66b173ac2a281cc29659e03790cfb5d666a

**Comment by olliwang** [comment]
MetalNanoVG now officially requires ARC. https://github.com/ollix/MetalNanoVG/commit/8c212e8aff0d15fc7959886c46e031103867ab99
