### ISSUE TITLE
mtlnvg__renderCreate: MTLLibrary leaked

### ISSUE THREAD

**Issue by wtholliday** [ollix/MetalNanoVG#7]
<img width="170" alt="leak" src="https://user-images.githubusercontent.com/841144/41082443-39e24a9e-69e3-11e8-815d-5b448f3c5a80.png">

**Comment by olliwang** [comment]
Just fixed. https://github.com/ollix/MetalNanoVG/commit/80ec89fff0e1f698822a46774d81beeed1ae11ba

**Comment by wtholliday** [comment]
Thanks!
