### ISSUE TITLE
static analyzer reports spurious memory leak

### ISSUE THREAD

**Issue by wtholliday** [ollix/MetalNanoVG#8]
<img width="1663" alt="screen shot 2018-06-24 at 3 55 09 pm" src="https://user-images.githubusercontent.com/841144/41824571-48492430-77c7-11e8-9eca-8e95dc4eb2e7.png">

The `MTLDevice` is a singleton (I checked), but it would be good to fix this warning anyway. I think all that is needed is a call to `release` after assigning to `metalLayer->device`.

**Comment by olliwang** [comment]
How about releasing it in `mtlnvg__renderDelete()`?

**Comment by wtholliday** [comment]
I think this is what you should do: https://github.com/wtholliday/MetalNanoVG/commit/df4da4aab698bb462d678dff5dea87d479bcc313

**Comment by olliwang** [comment]
Oh, thanks. 👍
